/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import codigo.PermissaoAcesso;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.text.MaskFormatter;


/**
 *
 * @author USUARIO
 */
public class TelaPrincipal extends javax.swing.JFrame {

    static String info = null;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        restringirAcesso();        
    }
    
    /**
     *Método para mostrar ao usuário restritamente o que foi permitido a ele
     */
    public void restringirAcesso(){
        //verificar permissão
        switch (PermissaoAcesso.getTipoAcesso()) {
                    case 1://instrutor
                        jMFuncionarios.setVisible(false);
                        jMAlunos.setVisible(false);
                        jMRelatorios.setVisible(false);
                        jMConfiguracoes.setVisible(false);
                        jMCadastrarCursos.setVisible(false);
                        jMAtualizarExcluirCursos.setVisible(false);
                        jMCadastrarAutoEscola.setVisible(false);
                        jMCadastrarTurmas.setVisible(false);
                        jMCadastrarFuncionarios.setVisible(false);
                        jMAtualizarExcluirFuncionarios.setVisible(false);
                        jMCadastrarVeiculos.setVisible(false);
                        jMExcluirVeiculos.setVisible(false);
                        jMCadastrarAutoEscola.setVisible(false);
                        
                        
                        
                        break;
                    case 2: //diretor com acesso padrao
                        jMCadastrarCursos.setVisible(false);
                        jMAtualizarExcluirCursos.setVisible(false);
                        jMCadastrarTurmas.setVisible(false);
                        jMCadastrarFuncionarios.setVisible(false);
                        jMAtualizarExcluirFuncionarios.setVisible(false);
                        jMCadastrarVeiculos.setVisible(false);
                        jMExcluirVeiculos.setVisible(false);
                        jMCadastrarAluno.setVisible(false);
                        jMAtualizarExcluirAluno.setVisible(false);
                      
                        jMControleAulasPraticas.setVisible(false);
                        jMExames.setVisible(false);
                        
                        break;
                    case 3://atendente
                        jMRelatorios.setVisible(false);
                        jMCadastrarAutoEscola.setVisible(false);
                        break;
                        
                    default: //diretor com acesso total
                        System.out.println("Acesso privilegiado!");
                        break;
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDesktopPanel = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLNomeCFC = new javax.swing.JLabel();
        jLUsuarioLogado = new javax.swing.JLabel();
        jLImagemUsuario = new javax.swing.JLabel();
        jLDataAtual = new javax.swing.JLabel();
        jLHoraAtual = new javax.swing.JLabel();
        MenuTelaPrincipal = new javax.swing.JMenuBar();
        jMArquivo = new javax.swing.JMenu();
        jMCadastrarAutoEscola = new javax.swing.JMenuItem();
        jMAutoEscola = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMSair = new javax.swing.JMenuItem();
        jMCursos = new javax.swing.JMenu();
        jMCadastrarCursos = new javax.swing.JMenuItem();
        jMAtualizarExcluirCursos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMVisualizarCursos = new javax.swing.JMenuItem();
        jMTurmas = new javax.swing.JMenu();
        jMCadastrarTurmas = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMVisualizarTurmas = new javax.swing.JMenuItem();
        jMFuncionarios = new javax.swing.JMenu();
        jMCadastrarFuncionarios = new javax.swing.JMenuItem();
        jMAtualizarExcluirFuncionarios = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMVisualizarFuncionarios = new javax.swing.JMenuItem();
        jMVisualizarInstrutores = new javax.swing.JMenu();
        jMVisualizarInstrutoresPraticos = new javax.swing.JMenuItem();
        jMVisualizarInstrutoresTeoricos = new javax.swing.JMenuItem();
        jMVeiculos = new javax.swing.JMenu();
        jMCadastrarVeiculos = new javax.swing.JMenuItem();
        jMExcluirVeiculos = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMVisualizarVeiculos = new javax.swing.JMenu();
        jMVisualizarCategoriaA = new javax.swing.JMenuItem();
        jMVisualizarCategoriaB = new javax.swing.JMenuItem();
        jMVisualizarCategoriaC = new javax.swing.JMenuItem();
        jMVisualizarCategoriaD = new javax.swing.JMenuItem();
        jMVisualizarCategoriaE = new javax.swing.JMenuItem();
        jMAlunos = new javax.swing.JMenu();
        jMCadastrarAluno = new javax.swing.JMenuItem();
        jMAtualizarExcluirAluno = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMBuscarAluno = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMControleAulasPraticas = new javax.swing.JMenuItem();
        jMExames = new javax.swing.JMenu();
        jMMarcarExames = new javax.swing.JMenuItem();
        jMInserirNotas = new javax.swing.JMenuItem();
        jMRelatorios = new javax.swing.JMenu();
        jMMapaDeAulas = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMDesempenhoAlunos = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMSituacaoAlunos = new javax.swing.JMenuItem();
        jMRelacaoAlunosCategorias = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMConfiguracoes = new javax.swing.JMenu();
        jMCadastrarUsuario = new javax.swing.JMenuItem();
        jMAtualizarSenha = new javax.swing.JMenuItem();
        jMSobre = new javax.swing.JMenu();
        jMSobreSoftware = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema - Centro de Formação de Condutores");
        setBackground(new java.awt.Color(204, 204, 204));
        setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        setForeground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JDesktopPanel.setBackground(java.awt.Color.lightGray);
        JDesktopPanel.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout JDesktopPanelLayout = new javax.swing.GroupLayout(JDesktopPanel);
        JDesktopPanel.setLayout(JDesktopPanelLayout);
        JDesktopPanelLayout.setHorizontalGroup(
            JDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JDesktopPanelLayout.setVerticalGroup(
            JDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLNomeCFC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNomeCFC.setText("Nome CFC");

        jLUsuarioLogado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLUsuarioLogado.setText("Usuário Logado");

        jLImagemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/User.png"))); // NOI18N

        jLDataAtual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLDataAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLHoraAtual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLHoraAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLNomeCFC, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(525, 525, 525)
                .addComponent(jLImagemUsuario)
                .addGap(18, 18, 18)
                .addComponent(jLUsuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(97, 97, 97)
                .addComponent(jLDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLHoraAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLNomeCFC))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLImagemUsuario)
                        .addComponent(jLUsuarioLogado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLHoraAtual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLDataAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        MenuTelaPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        jMArquivo.setBackground(new java.awt.Color(204, 204, 255));
        jMArquivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMArquivo.setText("Arquivo");
        jMArquivo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMArquivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMArquivo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMArquivo.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMCadastrarAutoEscola.setText("Cadastrar CFC");
        jMCadastrarAutoEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarAutoEscolaActionPerformed(evt);
            }
        });
        jMArquivo.add(jMCadastrarAutoEscola);

        jMAutoEscola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Brick house.png"))); // NOI18N
        jMAutoEscola.setText("Dados CFC");
        jMAutoEscola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAutoEscolaActionPerformed(evt);
            }
        });
        jMArquivo.add(jMAutoEscola);
        jMArquivo.add(jSeparator1);

        jMSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Exit.png"))); // NOI18N
        jMSair.setText("Sair");
        jMSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSairActionPerformed(evt);
            }
        });
        jMArquivo.add(jMSair);

        MenuTelaPrincipal.add(jMArquivo);

        jMCursos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMCursos.setText("Cursos");
        jMCursos.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMCursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMCursos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMCursos.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMCadastrarCursos.setText("Cadastrar");
        jMCadastrarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarCursosActionPerformed(evt);
            }
        });
        jMCursos.add(jMCadastrarCursos);

        jMAtualizarExcluirCursos.setText("Atualizar/Excluir");
        jMAtualizarExcluirCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAtualizarExcluirCursosActionPerformed(evt);
            }
        });
        jMCursos.add(jMAtualizarExcluirCursos);
        jMCursos.add(jSeparator2);

        jMVisualizarCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Book.png"))); // NOI18N
        jMVisualizarCursos.setText("Visualizar Cursos");
        jMVisualizarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVisualizarCursosActionPerformed(evt);
            }
        });
        jMCursos.add(jMVisualizarCursos);

        MenuTelaPrincipal.add(jMCursos);

        jMTurmas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMTurmas.setText("Turmas");
        jMTurmas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMTurmas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMTurmas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMTurmas.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMCadastrarTurmas.setText("Cadastrar Turmas");
        jMCadastrarTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarTurmasActionPerformed(evt);
            }
        });
        jMTurmas.add(jMCadastrarTurmas);
        jMTurmas.add(jSeparator8);

        jMVisualizarTurmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Conference.png"))); // NOI18N
        jMVisualizarTurmas.setText("Visualizar Turmas");
        jMVisualizarTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVisualizarTurmasActionPerformed(evt);
            }
        });
        jMTurmas.add(jMVisualizarTurmas);

        MenuTelaPrincipal.add(jMTurmas);

        jMFuncionarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMFuncionarios.setText("Funcionários");
        jMFuncionarios.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMFuncionarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMFuncionarios.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMCadastrarFuncionarios.setText("Cadastrar");
        jMCadastrarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarFuncionariosActionPerformed(evt);
            }
        });
        jMFuncionarios.add(jMCadastrarFuncionarios);

        jMAtualizarExcluirFuncionarios.setText("Atualizar/Excluir");
        jMAtualizarExcluirFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAtualizarExcluirFuncionariosActionPerformed(evt);
            }
        });
        jMFuncionarios.add(jMAtualizarExcluirFuncionarios);
        jMFuncionarios.add(jSeparator3);

        jMVisualizarFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Users.png"))); // NOI18N
        jMVisualizarFuncionarios.setText("Visualizar Funcionários Administrativos");
        jMVisualizarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVisualizarFuncionariosActionPerformed(evt);
            }
        });
        jMFuncionarios.add(jMVisualizarFuncionarios);

        jMVisualizarInstrutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Clien list.png"))); // NOI18N
        jMVisualizarInstrutores.setText("Visualizar Instrutores");

        jMVisualizarInstrutoresPraticos.setText("Instrutores de Aulas Práticas");
        jMVisualizarInstrutoresPraticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVisualizarInstrutoresPraticosActionPerformed(evt);
            }
        });
        jMVisualizarInstrutores.add(jMVisualizarInstrutoresPraticos);

        jMVisualizarInstrutoresTeoricos.setText("Instrutores de Aulas Teóricas");
        jMVisualizarInstrutoresTeoricos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVisualizarInstrutoresTeoricosActionPerformed(evt);
            }
        });
        jMVisualizarInstrutores.add(jMVisualizarInstrutoresTeoricos);

        jMFuncionarios.add(jMVisualizarInstrutores);

        MenuTelaPrincipal.add(jMFuncionarios);

        jMVeiculos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMVeiculos.setText("Veículos");
        jMVeiculos.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMVeiculos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMVeiculos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMVeiculos.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMCadastrarVeiculos.setText("Cadastrar");
        jMCadastrarVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarVeiculosActionPerformed(evt);
            }
        });
        jMVeiculos.add(jMCadastrarVeiculos);

        jMExcluirVeiculos.setText("Excluir");
        jMExcluirVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMExcluirVeiculosActionPerformed(evt);
            }
        });
        jMVeiculos.add(jMExcluirVeiculos);
        jMVeiculos.add(jSeparator4);

        jMVisualizarVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CarroIcone.png"))); // NOI18N
        jMVisualizarVeiculos.setText("Visualizar Veículos");

        jMVisualizarCategoriaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CategoriaA.png"))); // NOI18N
        jMVisualizarCategoriaA.setText("Categoria A");
        jMVisualizarCategoriaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVisualizarCategoriaAActionPerformed(evt);
            }
        });
        jMVisualizarVeiculos.add(jMVisualizarCategoriaA);

        jMVisualizarCategoriaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CategoriaB.png"))); // NOI18N
        jMVisualizarCategoriaB.setText("Categoria B");
        jMVisualizarCategoriaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVisualizarCategoriaBActionPerformed(evt);
            }
        });
        jMVisualizarVeiculos.add(jMVisualizarCategoriaB);

        jMVisualizarCategoriaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CategoriaC.png"))); // NOI18N
        jMVisualizarCategoriaC.setText("Categoria C");
        jMVisualizarCategoriaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVisualizarCategoriaCActionPerformed(evt);
            }
        });
        jMVisualizarVeiculos.add(jMVisualizarCategoriaC);

        jMVisualizarCategoriaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CategoriaD.png"))); // NOI18N
        jMVisualizarCategoriaD.setText("Categoria D");
        jMVisualizarCategoriaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVisualizarCategoriaDActionPerformed(evt);
            }
        });
        jMVisualizarVeiculos.add(jMVisualizarCategoriaD);

        jMVisualizarCategoriaE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CategoriaE.png"))); // NOI18N
        jMVisualizarCategoriaE.setText("Categoria E");
        jMVisualizarCategoriaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVisualizarCategoriaEActionPerformed(evt);
            }
        });
        jMVisualizarVeiculos.add(jMVisualizarCategoriaE);

        jMVeiculos.add(jMVisualizarVeiculos);

        MenuTelaPrincipal.add(jMVeiculos);

        jMAlunos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMAlunos.setText("Alunos");
        jMAlunos.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMAlunos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMAlunos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMAlunos.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMCadastrarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/addusergroup_1251.png"))); // NOI18N
        jMCadastrarAluno.setText("Cadastrar");
        jMCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarAlunoActionPerformed(evt);
            }
        });
        jMAlunos.add(jMCadastrarAluno);

        jMAtualizarExcluirAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/edituser_1182.png"))); // NOI18N
        jMAtualizarExcluirAluno.setText("Atualizar/Excluir");
        jMAtualizarExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAtualizarExcluirAlunoActionPerformed(evt);
            }
        });
        jMAlunos.add(jMAtualizarExcluirAluno);
        jMAlunos.add(jSeparator5);

        jMBuscarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        jMBuscarAluno.setText("Buscar aluno");
        jMBuscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBuscarAlunoActionPerformed(evt);
            }
        });
        jMAlunos.add(jMBuscarAluno);
        jMAlunos.add(jSeparator6);
        jMAlunos.add(jSeparator7);

        jMControleAulasPraticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Tick.png"))); // NOI18N
        jMControleAulasPraticas.setText("Controle de aulas práticas");
        jMControleAulasPraticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMControleAulasPraticasActionPerformed(evt);
            }
        });
        jMAlunos.add(jMControleAulasPraticas);

        jMExames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Notes.png"))); // NOI18N
        jMExames.setText("Exames");

        jMMarcarExames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Date.png"))); // NOI18N
        jMMarcarExames.setText("Marcar exames");
        jMMarcarExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMMarcarExamesActionPerformed(evt);
            }
        });
        jMExames.add(jMMarcarExames);

        jMInserirNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Edit.png"))); // NOI18N
        jMInserirNotas.setText("Inserir notas");
        jMInserirNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMInserirNotasActionPerformed(evt);
            }
        });
        jMExames.add(jMInserirNotas);

        jMAlunos.add(jMExames);

        MenuTelaPrincipal.add(jMAlunos);

        jMRelatorios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMRelatorios.setText("Relatórios");
        jMRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMRelatorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMRelatorios.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMMapaDeAulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/agenda.png"))); // NOI18N
        jMMapaDeAulas.setText("Mapa de aulas");
        jMMapaDeAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMMapaDeAulasActionPerformed(evt);
            }
        });
        jMRelatorios.add(jMMapaDeAulas);
        jMRelatorios.add(jSeparator11);

        jMDesempenhoAlunos.setText("Desempenho alunos");
        jMDesempenhoAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDesempenhoAlunosActionPerformed(evt);
            }
        });
        jMRelatorios.add(jMDesempenhoAlunos);
        jMRelatorios.add(jSeparator10);

        jMSituacaoAlunos.setText("Situação alunos");
        jMSituacaoAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSituacaoAlunosActionPerformed(evt);
            }
        });
        jMRelatorios.add(jMSituacaoAlunos);

        jMRelacaoAlunosCategorias.setText("Relação alunos x categorias");
        jMRelacaoAlunosCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRelacaoAlunosCategoriasActionPerformed(evt);
            }
        });
        jMRelatorios.add(jMRelacaoAlunosCategorias);
        jMRelatorios.add(jSeparator9);

        MenuTelaPrincipal.add(jMRelatorios);

        jMConfiguracoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMConfiguracoes.setText("Configurações");
        jMConfiguracoes.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMConfiguracoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMConfiguracoes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMConfiguracoes.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMCadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Key.png"))); // NOI18N
        jMCadastrarUsuario.setText("Cadastrar Usuário");
        jMCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarUsuarioActionPerformed(evt);
            }
        });
        jMConfiguracoes.add(jMCadastrarUsuario);

        jMAtualizarSenha.setText("Atualizar Senha");
        jMAtualizarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAtualizarSenhaActionPerformed(evt);
            }
        });
        jMConfiguracoes.add(jMAtualizarSenha);

        MenuTelaPrincipal.add(jMConfiguracoes);

        jMSobre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMSobre.setText("Sobre");
        jMSobre.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jMSobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMSobre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMSobre.setMaximumSize(new java.awt.Dimension(120, 32767));

        jMSobreSoftware.setBackground(new java.awt.Color(204, 204, 255));
        jMSobreSoftware.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Info.png"))); // NOI18N
        jMSobreSoftware.setText("Sobre");
        jMSobreSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSobreSoftwareActionPerformed(evt);
            }
        });
        jMSobre.add(jMSobreSoftware);

        MenuTelaPrincipal.add(jMSobre);

        setJMenuBar(MenuTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPanel)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JDesktopPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMVisualizarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVisualizarFuncionariosActionPerformed
        // TODO add your handling code here:
        TelaVisualizarFuncionarios visualizar = new TelaVisualizarFuncionarios();
        JDesktopPanel.add(visualizar);
        visualizar.setTipoVisualizacao("ADMINISTRATIVO");

        visualizar.setPosicao();
    }//GEN-LAST:event_jMVisualizarFuncionariosActionPerformed

    private void jMVisualizarCategoriaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVisualizarCategoriaBActionPerformed
         // TODO add your handling code here:
        TelaVisualizarVeiculos visualizar = new TelaVisualizarVeiculos();
        JDesktopPanel.add(visualizar);
        visualizar.exibir("B");
        visualizar.setPosicao();
    }//GEN-LAST:event_jMVisualizarCategoriaBActionPerformed

    private void jMVisualizarCategoriaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVisualizarCategoriaDActionPerformed
        // TODO add your handling code here:
        TelaVisualizarVeiculos visualizar = new TelaVisualizarVeiculos();
        JDesktopPanel.add(visualizar);
        visualizar.exibir("D");
        visualizar.setPosicao();
    }//GEN-LAST:event_jMVisualizarCategoriaDActionPerformed

    private void jMMarcarExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMMarcarExamesActionPerformed
        // TODO add your handling code here:
        TelaMarcarExames tela = new TelaMarcarExames();
        JDesktopPanel.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
    }//GEN-LAST:event_jMMarcarExamesActionPerformed

    private void jMAutoEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAutoEscolaActionPerformed
        
        TelaDadosCFC telaDadosAutoEscola = new TelaDadosCFC();
        JDesktopPanel.add(telaDadosAutoEscola);
        telaDadosAutoEscola.setVisible(true);
        telaDadosAutoEscola.setPosicao();

    }//GEN-LAST:event_jMAutoEscolaActionPerformed

    private void jMSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSairActionPerformed
        // Fecha a aplicação ao clicar para sair
        System.exit(0);

    }//GEN-LAST:event_jMSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //abrir o sistema já maximizado
        this.setExtendedState(MAXIMIZED_BOTH);

        //abrir com o nome da autoescola
        //data
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jLDataAtual.setText(formato.format(dataSistema));

        //hora
        Timer timer = new Timer(1000, new hora());
        timer.start();

        //mostrar nome da Autoescola  na barra inferior do programa
        jLNomeCFC.setText(PermissaoAcesso.getAutoEscola());
        
        //mostrar usuario logado
        jLUsuarioLogado.setText(PermissaoAcesso.getUser());

    }//GEN-LAST:event_formWindowOpened

    private void jMCadastrarAutoEscolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarAutoEscolaActionPerformed
        TelaCadastrarCFC telaCadastrarCFC = new TelaCadastrarCFC();
        JDesktopPanel.add(telaCadastrarCFC);
        telaCadastrarCFC.setVisible(true);
        telaCadastrarCFC.setPosicao();
    }//GEN-LAST:event_jMCadastrarAutoEscolaActionPerformed

    private void jMSobreSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSobreSoftwareActionPerformed
       InformacaoSoftware sobre = new InformacaoSoftware();
        JDesktopPanel.add(sobre);
        sobre.setVisible(true);
        sobre.setPosicao();
    }//GEN-LAST:event_jMSobreSoftwareActionPerformed

    /**
     * Botão cadastrar curso.
     *
     * @param evt
     */
    private void jMCadastrarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarCursosActionPerformed
        TelaCadastrarCurso cadastrarcurso = new TelaCadastrarCurso();
        JDesktopPanel.add(cadastrarcurso);
        cadastrarcurso.setBotoes(false);
        cadastrarcurso.setVisible(true);
        cadastrarcurso.setPosicao();

    }//GEN-LAST:event_jMCadastrarCursosActionPerformed

    /**
     * Botão Atualizar/Excluir Curso.
     *
     * @param evt
     */
    private void jMAtualizarExcluirCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAtualizarExcluirCursosActionPerformed
        info = JOptionPane.showInputDialog("Informe o nome do Curso que deseja Atualizar ou Excluir: ");
        if (info.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe um nome válido");
        } else {
            TelaCadastrarCurso cadastrarcurso = new TelaCadastrarCurso();
            JDesktopPanel.add(cadastrarcurso);
            cadastrarcurso.setBotoes(true);
            cadastrarcurso.AttExcluir(info);
            cadastrarcurso.setVisible(true);
            cadastrarcurso.setPosicao();
        }
    }//GEN-LAST:event_jMAtualizarExcluirCursosActionPerformed

    private void jMVisualizarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVisualizarCursosActionPerformed

       TelaVisualizarCursos visualizar = new TelaVisualizarCursos();
        JDesktopPanel.add(visualizar);
        visualizar.setVisible(true);
        visualizar.setPosicao();
    }//GEN-LAST:event_jMVisualizarCursosActionPerformed
/**
     * Tela cadastrar turmas.
     *
     * @param evt
     */
    private void jMCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarUsuarioActionPerformed
         
        TelaCadastrarUsuarioSenha telaCadastrarUsuario=new TelaCadastrarUsuarioSenha();
        JDesktopPanel.add(telaCadastrarUsuario);
        telaCadastrarUsuario.setVisible(true);
        telaCadastrarUsuario.setPosicao();
        
    }//GEN-LAST:event_jMCadastrarUsuarioActionPerformed

    private void jMAtualizarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAtualizarSenhaActionPerformed
        TelaAtualizarUsuarioSenha telaAtualizarUsuario=new TelaAtualizarUsuarioSenha();
        JDesktopPanel.add(telaAtualizarUsuario);
        telaAtualizarUsuario.setVisible(true);
        telaAtualizarUsuario.setPosicao();
    }//GEN-LAST:event_jMAtualizarSenhaActionPerformed

    private void jMMapaDeAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMMapaDeAulasActionPerformed
        TelaMapadeAulas mapa = null;
        try {
            mapa = new TelaMapadeAulas();
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JDesktopPanel.add(mapa);
        mapa.setVisible(true);
       mapa.setTamanho();
    }//GEN-LAST:event_jMMapaDeAulasActionPerformed

    private void jMRelacaoAlunosCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRelacaoAlunosCategoriasActionPerformed
        TelaRelatorioCategoriasAlunos cat=new TelaRelatorioCategoriasAlunos();
        JDesktopPanel.add(cat);
        cat.setVisible(true);
       cat.setTamanho();
    }//GEN-LAST:event_jMRelacaoAlunosCategoriasActionPerformed

    private void jMSituacaoAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSituacaoAlunosActionPerformed
        TelaRelatorioSituacaoAlunos telaSitAluno=new TelaRelatorioSituacaoAlunos();
        JDesktopPanel.add(telaSitAluno);
        telaSitAluno.setVisible(true);
        telaSitAluno.setTamanho();
    }//GEN-LAST:event_jMSituacaoAlunosActionPerformed

    private void jMDesempenhoAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDesempenhoAlunosActionPerformed
        TelaRelatorioDesempenhoAlunos desempenhoAlunos=new TelaRelatorioDesempenhoAlunos();
        desempenhoAlunos.setVisible(true);
        JDesktopPanel.add(desempenhoAlunos);
        desempenhoAlunos.setVisible(true);
        desempenhoAlunos.setTamanho();
    }//GEN-LAST:event_jMDesempenhoAlunosActionPerformed

    /**
     * Tela cadastrar turmas.
     *
     * @param evt
     */
    private void jMCadastrarTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarTurmasActionPerformed
        // TODO add your handling code here:
        TelaCadastrarTurma cadastrar = new TelaCadastrarTurma();
        JDesktopPanel.add(cadastrar);
        cadastrar.setVisible(true);
        cadastrar.setPosicao();
    }//GEN-LAST:event_jMCadastrarTurmasActionPerformed

    private void jMCadastrarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarFuncionariosActionPerformed
        // TODO add your handling code here:
        TelaCadastrarFuncionario cadastrar = new TelaCadastrarFuncionario();
        JDesktopPanel.add(cadastrar);
        cadastrar.setVisible(true);
        cadastrar.setPosicao();
        cadastrar.botoes(false);
    }//GEN-LAST:event_jMCadastrarFuncionariosActionPerformed

    private void jMAtualizarExcluirFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAtualizarExcluirFuncionariosActionPerformed
        // TODO add your handling code here:

        String[] choices = {"ADMINISTRATIVO", "INSTRUTOR", "DIRETOR"};
        String tipo = (String) JOptionPane.showInputDialog(null, "Escolha a categoria do funcionário: ",
                "Atualizar/Excluir", JOptionPane.QUESTION_MESSAGE, null, // Use
                // default
                // icon
                choices, // Array of choices
                choices[0]); // Initial choice

        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("###.###.###-##");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe o CPF que deseja Atualizar/Excluir: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});

        String cpf = texto.getText();
        TelaCadastrarFuncionario tela = new TelaCadastrarFuncionario();
        JDesktopPanel.add(tela);

        tela.AtualizarExcluir(tipo, cpf);
        tela.botoes(true);
    }//GEN-LAST:event_jMAtualizarExcluirFuncionariosActionPerformed

    private void jMCadastrarVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarVeiculosActionPerformed
         // TODO add your handling code here:
        TelaCadastrarVeiculos cadastrar = new TelaCadastrarVeiculos();
        JDesktopPanel.add(cadastrar);
        cadastrar.botoes(true);
        cadastrar.setVisible(true);
        cadastrar.setPosicao();
    }//GEN-LAST:event_jMCadastrarVeiculosActionPerformed

    private void jMExcluirVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMExcluirVeiculosActionPerformed
        // TODO add your handling code here:
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter("AAA####");
        } catch (ParseException ex) {
        }
        JLabel label = new JLabel("Informe a placa do veículo que deseja Excluir: ");
        JFormattedTextField texto = new JFormattedTextField(formato);
        //UIManager.put("OptionPane.okButtonText", "Pesquisar");
        JOptionPane.showMessageDialog(null, new Object[]{label, texto});
        String placa = texto.getText();

        TelaCadastrarVeiculos cadastrar = new TelaCadastrarVeiculos();
        JDesktopPanel.add(cadastrar);
        cadastrar.botoes(false);

        cadastrar.setVisible(true);
        cadastrar.setPosicao();
        cadastrar.ExcluirVeiculo(placa);
    }//GEN-LAST:event_jMExcluirVeiculosActionPerformed

    private void jMVisualizarCategoriaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVisualizarCategoriaAActionPerformed
        // TODO add your handling code here:
        TelaVisualizarVeiculos visualizar = new TelaVisualizarVeiculos();
        JDesktopPanel.add(visualizar);
        visualizar.exibir("A");
        visualizar.setPosicao();
    }//GEN-LAST:event_jMVisualizarCategoriaAActionPerformed

    private void jMVisualizarCategoriaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVisualizarCategoriaCActionPerformed
         // TODO add your handling code here:
        TelaVisualizarVeiculos visualizar = new TelaVisualizarVeiculos();
        JDesktopPanel.add(visualizar);
        visualizar.exibir("C");
        visualizar.setPosicao();
    }//GEN-LAST:event_jMVisualizarCategoriaCActionPerformed

    private void jMVisualizarCategoriaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVisualizarCategoriaEActionPerformed
         // TODO add your handling code here:
        TelaVisualizarVeiculos visualizar = new TelaVisualizarVeiculos();
        JDesktopPanel.add(visualizar);
        visualizar.exibir("E");
        visualizar.setPosicao();
    }//GEN-LAST:event_jMVisualizarCategoriaEActionPerformed

    private void jMCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarAlunoActionPerformed
        // TODO add your handling code here:
        TelaCadastrarAlunos cadastrar = new TelaCadastrarAlunos();
        JDesktopPanel.add(cadastrar);
        cadastrar.setVisible(true);
        cadastrar.setPosicao();
        cadastrar.botoes(false);
    }//GEN-LAST:event_jMCadastrarAlunoActionPerformed

    private void jMAtualizarExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAtualizarExcluirAlunoActionPerformed
         // TODO add your handling code here:
        MaskFormatter formato = null;
        String procura;
        String[] choices = {"SELECIONE", "MATRICULA", "CPF"};
        String tipo = (String) JOptionPane.showInputDialog(null, "Escolha como deseja procurar o Aluno: ",
                "Atualizar/Excluir", JOptionPane.QUESTION_MESSAGE, null, // Use
                // default
                // icon
                choices, // Array of choices
                choices[0]); // Initial choice
        if (tipo.equals("SELECIONE")) {
            JOptionPane.showMessageDialog(null, "Selecione um tipo válido!");
        } else {
            if (tipo.equals("CPF")) {

                try {
                    formato = new MaskFormatter("###.###.###-##");
                } catch (ParseException ex) {
                }
                JLabel label = new JLabel("Informe o CPF que deseja Atualizar/Excluir: ");
                JFormattedTextField texto = new JFormattedTextField(formato);
                //UIManager.put("OptionPane.okButtonText", "Pesquisar");
                JOptionPane.showMessageDialog(null, new Object[]{label, texto});
                procura = texto.getText();
            } else {
                procura = JOptionPane.showInputDialog(null, "Informe a matrícula que deseja Atualizar/Excluir: ");
            }

            TelaCadastrarAlunos tela = new TelaCadastrarAlunos();
            JDesktopPanel.add(tela);
            tela.AtualizarExcluir(tipo, procura);
            tela.botoes(true);
        }
    }//GEN-LAST:event_jMAtualizarExcluirAlunoActionPerformed

    private void jMBuscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBuscarAlunoActionPerformed
         // TODO add your handling code here:
        // TODO add your handling code here:
        MaskFormatter formato = null;
        String procura;
        String[] choices = {"SELECIONE", "MATRICULA", "CPF"};
        String tipo = (String) JOptionPane.showInputDialog(null, "Escolha como deseja procurar o Aluno: ",
                "", JOptionPane.QUESTION_MESSAGE, null, // Use
                // default
                // icon
                choices, // Array of choices
                choices[0]); // Initial choice
        System.out.println(tipo);
        if (tipo.equals("SELECIONE")) {
            JOptionPane.showMessageDialog(null, "Selecione um tipo válido!");
        } else {
            if (tipo.equals("CPF")) {

                try {
                    formato = new MaskFormatter("###.###.###-##");
                } catch (ParseException ex) {
                }
                JLabel label = new JLabel("Informe o CPF que deseja Buscar: ");
                JFormattedTextField texto = new JFormattedTextField(formato);
                //UIManager.put("OptionPane.okButtonText", "Pesquisar");
                JOptionPane.showMessageDialog(null, new Object[]{label, texto});
                procura = texto.getText();
            } else {
                procura = JOptionPane.showInputDialog(null, "Informe a matrícula que deseja Busca: ");
            }
            System.out.println(procura);
            TelaCadastrarAlunos tela = new TelaCadastrarAlunos();
            JDesktopPanel.add(tela);
tela.setPosicao();
            tela.procura(tipo, procura);
        }
    }//GEN-LAST:event_jMBuscarAlunoActionPerformed

    private void jMVisualizarInstrutoresPraticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVisualizarInstrutoresPraticosActionPerformed
         // TODO add your handling code here:
        TelaVisualizarFuncionarios visualizar = new TelaVisualizarFuncionarios();
        JDesktopPanel.add(visualizar);
        visualizar.setTipoVisualizacao("PRATICO");

        visualizar.setPosicao();
    }//GEN-LAST:event_jMVisualizarInstrutoresPraticosActionPerformed

    private void jMVisualizarInstrutoresTeoricosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVisualizarInstrutoresTeoricosActionPerformed
        // TODO add your handling code here:
          TelaVisualizarFuncionarios visualizar = new TelaVisualizarFuncionarios();
        JDesktopPanel.add(visualizar);
        visualizar.setTipoVisualizacao("TEORICO");

        visualizar.setPosicao();
    }//GEN-LAST:event_jMVisualizarInstrutoresTeoricosActionPerformed

    private void jMVisualizarTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVisualizarTurmasActionPerformed
        // TODO add your handling code here:
        TelaVisualizarTurmas visualizar = new TelaVisualizarTurmas();
        JDesktopPanel.add(visualizar);
        visualizar.setVisible(true);

        visualizar.setPosicao();
    }//GEN-LAST:event_jMVisualizarTurmasActionPerformed

    private void jMControleAulasPraticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMControleAulasPraticasActionPerformed
        // TODO add your handling code here:
        TelaControleAulasPraticas tela = new TelaControleAulasPraticas();
          JDesktopPanel.add(tela);
        tela.setVisible(true);

        tela.setPosicao();
       
    }//GEN-LAST:event_jMControleAulasPraticasActionPerformed

    private void jMInserirNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMInserirNotasActionPerformed
        // TODO add your handling code here:
        TelaResultadoProvas visualizar = new TelaResultadoProvas();
        JDesktopPanel.add(visualizar);
        visualizar.setVisible(true);

        visualizar.setPosicao();
    }//GEN-LAST:event_jMInserirNotasActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDesktopPanel;
    private javax.swing.JMenuBar MenuTelaPrincipal;
    private javax.swing.JLabel jLDataAtual;
    private javax.swing.JLabel jLHoraAtual;
    private javax.swing.JLabel jLImagemUsuario;
    private javax.swing.JLabel jLNomeCFC;
    private javax.swing.JLabel jLUsuarioLogado;
    private javax.swing.JMenu jMAlunos;
    private javax.swing.JMenu jMArquivo;
    private javax.swing.JMenuItem jMAtualizarExcluirAluno;
    private javax.swing.JMenuItem jMAtualizarExcluirCursos;
    private javax.swing.JMenuItem jMAtualizarExcluirFuncionarios;
    private javax.swing.JMenuItem jMAtualizarSenha;
    private javax.swing.JMenuItem jMAutoEscola;
    private javax.swing.JMenuItem jMBuscarAluno;
    private javax.swing.JMenuItem jMCadastrarAluno;
    private javax.swing.JMenuItem jMCadastrarAutoEscola;
    private javax.swing.JMenuItem jMCadastrarCursos;
    private javax.swing.JMenuItem jMCadastrarFuncionarios;
    private javax.swing.JMenuItem jMCadastrarTurmas;
    private javax.swing.JMenuItem jMCadastrarUsuario;
    private javax.swing.JMenuItem jMCadastrarVeiculos;
    private javax.swing.JMenu jMConfiguracoes;
    private javax.swing.JMenuItem jMControleAulasPraticas;
    private javax.swing.JMenu jMCursos;
    private javax.swing.JMenuItem jMDesempenhoAlunos;
    private javax.swing.JMenu jMExames;
    private javax.swing.JMenuItem jMExcluirVeiculos;
    private javax.swing.JMenu jMFuncionarios;
    private javax.swing.JMenuItem jMInserirNotas;
    private javax.swing.JMenuItem jMMapaDeAulas;
    private javax.swing.JMenuItem jMMarcarExames;
    private javax.swing.JMenuItem jMRelacaoAlunosCategorias;
    private javax.swing.JMenu jMRelatorios;
    private javax.swing.JMenuItem jMSair;
    private javax.swing.JMenuItem jMSituacaoAlunos;
    private javax.swing.JMenu jMSobre;
    private javax.swing.JMenuItem jMSobreSoftware;
    private javax.swing.JMenu jMTurmas;
    private javax.swing.JMenu jMVeiculos;
    private javax.swing.JMenuItem jMVisualizarCategoriaA;
    private javax.swing.JMenuItem jMVisualizarCategoriaB;
    private javax.swing.JMenuItem jMVisualizarCategoriaC;
    private javax.swing.JMenuItem jMVisualizarCategoriaD;
    private javax.swing.JMenuItem jMVisualizarCategoriaE;
    private javax.swing.JMenuItem jMVisualizarCursos;
    private javax.swing.JMenuItem jMVisualizarFuncionarios;
    private javax.swing.JMenu jMVisualizarInstrutores;
    private javax.swing.JMenuItem jMVisualizarInstrutoresPraticos;
    private javax.swing.JMenuItem jMVisualizarInstrutoresTeoricos;
    private javax.swing.JMenuItem jMVisualizarTurmas;
    private javax.swing.JMenu jMVisualizarVeiculos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent ae) {
            Calendar now = Calendar.getInstance();
            jLHoraAtual.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
}
