/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ConexaoPostgres.Conexao;
import codigo.PermissaoAcesso;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.beans.PropertyVetoException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author USUARIO
 */
public class TelaMapadeAulas extends javax.swing.JInternalFrame {

    /**
     * Creates new form MapaAulas
     */
    public TelaMapadeAulas() throws IOException {
       
        initComponents();
      

        gerarRelatorio();
        

    }
    
    /**
     *Método para fazer o relatório parecer folha A4
     */
    public void setTamanho(){
        jPanelImprimir.setSize(595, 900);      
        this.setMaximizable(true);
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaRelatorioDesempenhoAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     *Método preenche o relatorio de mapas de aulas
     */
    public void gerarRelatorio() {
        //nome CFC
        jLabelNomeCFC.setText(PermissaoAcesso.getAutoEscola());
        ResultSet rs = null;
        Conexao con = new Conexao();
        String busca = "select C.nome,T.id_turmas,T.horario,F.nome "
                + "from funcionario F, turmas_teoricas T, cursos C "
                + "where T.id_curso=C.id_curso and T.cpf_func=F.cpf_func and F.id_aut=" + PermissaoAcesso.getIdAutoEscola();

        PreparedStatement ps = null;

        try {
            ps = con.getConexao().prepareStatement(busca);
            rs = ps.executeQuery();
            jTableMapaAulas.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(TelaDadosCFC.class.getName()).log(Level.SEVERE, null, ex);
        }
        //nome endereço e telefones da CFC
        rs = null;
        con = new Conexao();
        String buscaEndTel = "SELECT telefone1,telefone2,end_cep,end_cidade,end_rua,end_numero,end_bairro FROM auto_escola WHERE id_aut=" + PermissaoAcesso.getIdAutoEscola();

        rs = con.executaBusca(buscaEndTel);
        String telefone = null;
        String celular = null;
        String cep = null;
        String cidade = null;
        String rua = null;
        String numero = null;
        String bairro = null;
        try {
            while (rs.next()) {
                telefone = rs.getString("telefone1");
                celular = rs.getString("telefone2");
                cep = rs.getString("end_cep");
                cidade = rs.getString("end_cidade");
                rua = rs.getString("end_rua");
                numero = rs.getString("end_numero");
                bairro = rs.getString("end_bairro");

            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaDadosCFC.class.getName()).log(Level.SEVERE, null, ex);
        }
        String end=rua + ", n. " + numero + ", bairro: " + bairro + ", " + cep + ", " + cidade;
        String tel=telefone+" / "+celular;
        jLabelTelefones.setText(tel);
        jLabelendereco.setText(end);
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelImprimir = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMapaAulas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabelendereco = new javax.swing.JLabel();
        jLabelTelefones = new javax.swing.JLabel();
        jLabelNomeCFC = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);

        jPanelImprimir.setBackground(new java.awt.Color(255, 255, 255));
        jPanelImprimir.setMaximumSize(new java.awt.Dimension(595, 824));
        jPanelImprimir.setMinimumSize(new java.awt.Dimension(595, 824));
        jPanelImprimir.setPreferredSize(new java.awt.Dimension(595, 824));

        jTableMapaAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableMapaAulas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mapa de Aulas");

        jLabelendereco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelendereco.setText("Endereço");

        jLabelTelefones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTelefones.setText("Telefone");

        jLabelNomeCFC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeCFC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeCFC.setText("Nome CFC");

        javax.swing.GroupLayout jPanelImprimirLayout = new javax.swing.GroupLayout(jPanelImprimir);
        jPanelImprimir.setLayout(jPanelImprimirLayout);
        jPanelImprimirLayout.setHorizontalGroup(
            jPanelImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTelefones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelNomeCFC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelendereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelImprimirLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanelImprimirLayout.setVerticalGroup(
            jPanelImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImprimirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeCFC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabelTelefones)
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)
                .addComponent(jLabelendereco)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanelImprimir);
        jPanelImprimir.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNomeCFC;
    private javax.swing.JLabel jLabelTelefones;
    private javax.swing.JLabel jLabelendereco;
    private javax.swing.JPanel jPanelImprimir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMapaAulas;
    // End of variables declaration//GEN-END:variables

}
