/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ConexaoPostgres.Conexao;
import codigo.OperacoesBancoDeDados;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class TelaCadastrarCFC extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarAutoEscola
     */
    public TelaCadastrarCFC() {
        initComponents();
        //só vai conseguir inserir informações se clicar em novo
        jTNomeCFC.setEditable(false);
        jCTipoEstabelecimento.setEnabled(false);
        jFTTelefone.setEditable(false);
        jFTCelular.setEditable(false);
        jFTCEP.setEditable(false);
        jTRua.setEditable(false);
        jTBairro.setEditable(false);
        jTNumero.setEditable(false);
        jTCidade.setEditable(false);
        jBGravarCFC.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTNomeCFC = new javax.swing.JTextField();
        jCTipoEstabelecimento = new javax.swing.JComboBox<>();
        jFTCelular = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFTTelefone = new javax.swing.JFormattedTextField();
        jLabel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jFTCEP = new javax.swing.JFormattedTextField();
        jTNumero = new javax.swing.JTextField();
        jTRua = new javax.swing.JTextField();
        jTCidade = new javax.swing.JTextField();
        jTBairro = new javax.swing.JTextField();
        jBNovoCFC = new javax.swing.JButton();
        jBCancelarCFC = new javax.swing.JButton();
        jBGravarCFC = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar CFC");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DADOS GERAIS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Telefone:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tipo de estabelecimento:");

        jTNomeCFC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCTipoEstabelecimento.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jCTipoEstabelecimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCTipoEstabelecimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Matriz", "Filial" }));
        jCTipoEstabelecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTipoEstabelecimentoActionPerformed(evt);
            }
        });

        try {
            jFTCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Celular:");

        try {
            jFTTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENDEREÇO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Rua:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("CEP:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Número:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Bairro:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cidade:");

        try {
            jFTCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTCEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTRua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jBNovoCFC.setText("NOVO");
        jBNovoCFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoCFCActionPerformed(evt);
            }
        });

        jBCancelarCFC.setText("CANCELAR");
        jBCancelarCFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarCFCActionPerformed(evt);
            }
        });

        jBGravarCFC.setText("GRAVAR");
        jBGravarCFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarCFCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLabelLayout = new javax.swing.GroupLayout(jLabel);
        jLabel.setLayout(jLabelLayout);
        jLabelLayout.setHorizontalGroup(
            jLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(113, 113, 113)
                .addGroup(jLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFTCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTBairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                        .addComponent(jTRua, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBNovoCFC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jBCancelarCFC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jBGravarCFC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jLabelLayout.setVerticalGroup(
            jLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(jLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(jLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBGravarCFC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBCancelarCFC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBNovoCFC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jBNovoCFC.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jCTipoEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(114, 114, 114)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jFTTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFTCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTNomeCFC, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jCTipoEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTNomeCFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFTTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jFTCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNovoCFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoCFCActionPerformed
        jTNomeCFC.setEditable(true);
        jCTipoEstabelecimento.setEnabled(true);
        jFTTelefone.setEditable(true);
        jFTCelular.setEditable(true);
        jFTCEP.setEditable(true);
        jTRua.setEditable(true);
        jTBairro.setEditable(true);
        jTNumero.setEditable(true);
        jTCidade.setEditable(true);
        jBGravarCFC.setEnabled(true);

        jTNomeCFC.setText("");
        jCTipoEstabelecimento.setSelectedIndex(0);
        jFTTelefone.setText("");
        jFTCelular.setText("");
        jFTCEP.setText("");
        jTRua.setText("");
        jTBairro.setText("");
        jTNumero.setText("");
        jTCidade.setText("");

        jBGravarCFC.setEnabled(true);
    }//GEN-LAST:event_jBNovoCFCActionPerformed

    private void jBCancelarCFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarCFCActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarCFCActionPerformed

    private void jBGravarCFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarCFCActionPerformed

        //String id_aut = "defaut";
        String nome = jTNomeCFC.getText();
        String matriz_ou_filial = jCTipoEstabelecimento.getSelectedItem().toString();
        String telefone = jFTTelefone.getText();
        String cep = jFTCEP.getText();
        String cidade = jTCidade.getText();
        String rua = jTRua.getText();
        String numero = jTNumero.getText();
        String bairro = jTBairro.getText();
        String telefone1 = jFTCelular.getText(); //esse pode assumir valor null
        int resultado;
        ResultSet rs = null;
        String nomeMatriz = "";
        Conexao con = new Conexao();

        if ((!nome.equals("")) && (!matriz_ou_filial.equals("Selecione")) && (!telefone.equals(""))
                && (!cep.equals("")) && (!cidade.equals("")) && (!rua.equals("")) && (!numero.equals("")) && (!bairro.equals(""))) {
            String verificaMatriz = "SELECT nome "
                    + "FROM auto_escola"
                    + " WHERE matriz_ou_filial='Matriz'";
            rs = con.executaBusca(verificaMatriz);
            try {
                while (rs.next()) {
                    nomeMatriz = rs.getString("nome");
                }
                System.out.println("nomeMatriz: " + nomeMatriz);
            } catch (SQLException ex) {
                Logger.getLogger(TelaCadastrarCFC.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (matriz_ou_filial.equals("Matriz")) {
                try {
                    if (nomeMatriz == null || nomeMatriz == "") {

                        OperacoesBancoDeDados inserir = new OperacoesBancoDeDados();
                        String tabela = "auto_escola(id_aut,nome,matriz_ou_filial,telefone1,end_cep,end_cidade,end_rua,end_numero,end_bairro,telefone2)";
                        String valores = "(" + "default" + ",'" + nome + "','" + matriz_ou_filial
                                + "','" + telefone + "','" + cep + "','" + cidade + "','"
                                + rua + "','" + numero + "','" + bairro + "','" + telefone1 + "')";
                        resultado = inserir.inserirLinhasBD(tabela, valores);
                        if (resultado > 0) {
                            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                            jTNomeCFC.setText("");
                            jCTipoEstabelecimento.setSelectedIndex(0);
                            jFTTelefone.setText("");
                            jFTCelular.setText("");
                            jFTCEP.setText("");
                            jTRua.setText("");
                            jTBairro.setText("");
                            jTNumero.setText("");
                            jTCidade.setText("");
                        } else {
                            System.out.println("Entrou aqui 5!");
                            JOptionPane.showMessageDialog(null, "Erro durante Cadastrado. Tente novamente!");
                        }

                    } else {

                        JOptionPane.showMessageDialog(null, "A matriz já está cadastrada!");
                        jTNomeCFC.setText("");
                        jCTipoEstabelecimento.setSelectedIndex(0);
                        jFTTelefone.setText("");
                        jFTCelular.setText("");
                        jFTCEP.setText("");
                        jTRua.setText("");
                        jTBairro.setText("");
                        jTNumero.setText("");
                        jTCidade.setText("");
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else if (!matriz_ou_filial.equals("Matriz")) {
                OperacoesBancoDeDados inserir = new OperacoesBancoDeDados();
                String tabela = "auto_escola(id_aut,nome,matriz_ou_filial,telefone1,end_cep,end_cidade,end_rua,end_numero,end_bairro,telefone2)";
                String valores = "(" + "default" + ",'" + nome + "','" + matriz_ou_filial
                        + "','" + telefone + "','" + cep + "','" + cidade + "','"
                        + rua + "','" + numero + "','" + bairro + "','" + telefone1 + "')";
                resultado = inserir.inserirLinhasBD(tabela, valores);
                if (resultado > 0) {
                    JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro durante Cadastrado. Tente novamente!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Ainda há dados para serem preenchidos!");
        }


    }//GEN-LAST:event_jBGravarCFCActionPerformed

    private void jCTipoEstabelecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTipoEstabelecimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTipoEstabelecimentoActionPerformed

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelarCFC;
    private javax.swing.JButton jBGravarCFC;
    private javax.swing.JButton jBNovoCFC;
    private javax.swing.JComboBox<String> jCTipoEstabelecimento;
    private javax.swing.JFormattedTextField jFTCEP;
    private javax.swing.JFormattedTextField jFTCelular;
    private javax.swing.JFormattedTextField jFTTelefone;
    private javax.swing.JPanel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTBairro;
    private javax.swing.JTextField jTCidade;
    private javax.swing.JTextField jTNomeCFC;
    private javax.swing.JTextField jTNumero;
    private javax.swing.JTextField jTRua;
    // End of variables declaration//GEN-END:variables
}
