/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ConexaoPostgres.Conexao;
import codigo.OperacoesBancoDeDados;
import codigo.PermissaoAcesso;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author USUARIO
 */
public class TelaDadosCFC extends javax.swing.JInternalFrame {

    int idMatriz;
    private String nomeMatriz = "";
    private String matriz = "";
    private String telefoneMatriz = "";
    private String cepMatriz = "";
    private String cidadeMatriz = "";
    private String ruaMatriz = "";
    private String numeroMatriz = "";
    private String bairroMatriz = "";
    private String celularMatriz = "";
    int idFilial;
    private String nomeFilial = "";
    private String filial = "";
    private String telefoneFilial = "";
    private String cepFilial = "";
    private String cidadeFilial = "";
    private String ruaFilial = "";
    private String numeroFilial = "";
    private String bairroFilial = "";
    private String celularFilial = "";

    /**
     * Creates new form Relatorio
     */
    public TelaDadosCFC() {
        initComponents();
        /*Campos para atualizar dados da matriz estarão escondidos até que aperte o botão atualizar*/
        jLabel1Matriz.setVisible(false);
        jTNomeMatrizAlterar.setVisible(false);
        jTRuaMatrizAlterar.setVisible(false);
        jTNumeroMatrizAlterar.setVisible(false);
        jTCEPMatrizAlterar.setVisible(false);
        jTBairroMatrizAlterar.setVisible(false);
        jTCidadeMatrizAlterar.setVisible(false);
        jTCelularMatrizAlterar.setVisible(false);
        jTTelefoneMatrizAlterar.setVisible(false);
        jSeparator1.setVisible(false);
        jPEnderecoAlterarMatriz.setVisible(false);
        jLabel10AlterarMatriz.setVisible(false);
        jLabel11AlterarMatriz.setVisible(false);
        jLabel12AlterarMatriz.setVisible(false);
        jLabel13AlterarMatriz.setVisible(false);
        jLabel14AlterarMatriz.setVisible(false);
        jLabel6AlterarMatriz.setVisible(false);
        jLabel7AlterarMatriz.setVisible(false);
        jLabel8AlterarMatriz.setVisible(false);
        jBCancelarAlterarMatriz.setVisible(false);
        jBGravarAlterarMatriz.setVisible(false);

        /*Campos para atualizar dados da filial estarão escondidos até que aperte o botão atualizar*/
        jLabel6Filial.setVisible(false);
        jTNomeFilialAlterar.setVisible(false);
        jTRuaFilialAlterar.setVisible(false);
        jTNumeroFilialAlterar.setVisible(false);
        jTCEPFilialAlterar.setVisible(false);
        jTBairroFilialAlterar.setVisible(false);
        jTCidadeFilialAlterar.setVisible(false);
        jTCelularFilialAlterar.setVisible(false);
        jTTelefoneFilialAlterar.setVisible(false);
        jSeparatorFilialAlterar.setVisible(false);
        jPEnderecoAlterarFilial.setVisible(false);
        jLabel10AlterarFilial.setVisible(false);
        jLabel11AlterarFilial.setVisible(false);
        jLabel12AlterarFilial.setVisible(false);
        jLabel13AlterarFilial.setVisible(false);
        jLabel14AlterarFilial.setVisible(false);
        jLabel6AlterarFilial.setVisible(false);
        jLabel7AlterarFilial.setVisible(false);
        jLabel8AlterarFilial.setVisible(false);
        jBCancelarAlterarFilial.setVisible(false);
        jBGravarAlterarFilial.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jTPDadosCFC = new javax.swing.JTabbedPane();
        jPMatriz = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTCelularMatriz = new javax.swing.JTextField();
        jTEnderecoMatriz = new javax.swing.JTextField();
        jTNomeMatriz = new javax.swing.JTextField();
        jTTelefoneMatriz = new javax.swing.JTextField();
        jBAtualizarMatriz = new javax.swing.JButton();
        jLabel6AlterarMatriz = new javax.swing.JLabel();
        jTNomeMatrizAlterar = new javax.swing.JTextField();
        jLabel7AlterarMatriz = new javax.swing.JLabel();
        jTTelefoneMatrizAlterar = new javax.swing.JTextField();
        jLabel8AlterarMatriz = new javax.swing.JLabel();
        jTCelularMatrizAlterar = new javax.swing.JTextField();
        jPEnderecoAlterarMatriz = new javax.swing.JPanel();
        jTNumeroMatrizAlterar = new javax.swing.JTextField();
        jLabel10AlterarMatriz = new javax.swing.JLabel();
        jLabel11AlterarMatriz = new javax.swing.JLabel();
        jTBairroMatrizAlterar = new javax.swing.JTextField();
        jLabel12AlterarMatriz = new javax.swing.JLabel();
        jTCEPMatrizAlterar = new javax.swing.JTextField();
        jLabel13AlterarMatriz = new javax.swing.JLabel();
        jTRuaMatrizAlterar = new javax.swing.JTextField();
        jLabel14AlterarMatriz = new javax.swing.JLabel();
        jTCidadeMatrizAlterar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1Matriz = new javax.swing.JLabel();
        jBCancelarAlterarMatriz = new javax.swing.JButton();
        jBGravarAlterarMatriz = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTDiretorGeral = new javax.swing.JTextField();
        jTDiretorEnsino = new javax.swing.JTextField();
        jPFiliais = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFiliais = new javax.swing.JTable();
        jBAtualizarFilial = new javax.swing.JButton();
        jTNomeFilialAlterar = new javax.swing.JTextField();
        jLabel6AlterarFilial = new javax.swing.JLabel();
        jLabel7AlterarFilial = new javax.swing.JLabel();
        jTTelefoneFilialAlterar = new javax.swing.JTextField();
        jLabel8AlterarFilial = new javax.swing.JLabel();
        jTCelularFilialAlterar = new javax.swing.JTextField();
        jPEnderecoAlterarFilial = new javax.swing.JPanel();
        jTNumeroFilialAlterar = new javax.swing.JTextField();
        jLabel10AlterarFilial = new javax.swing.JLabel();
        jLabel11AlterarFilial = new javax.swing.JLabel();
        jTBairroFilialAlterar = new javax.swing.JTextField();
        jLabel12AlterarFilial = new javax.swing.JLabel();
        jTCEPFilialAlterar = new javax.swing.JTextField();
        jLabel13AlterarFilial = new javax.swing.JLabel();
        jTRuaFilialAlterar = new javax.swing.JTextField();
        jLabel14AlterarFilial = new javax.swing.JLabel();
        jTCidadeFilialAlterar = new javax.swing.JTextField();
        jBCancelarAlterarFilial = new javax.swing.JButton();
        jBGravarAlterarFilial = new javax.swing.JButton();
        jLabel6Filial = new javax.swing.JLabel();
        jSeparatorFilialAlterar = new javax.swing.JSeparator();

        setClosable(true);
        setForeground(new java.awt.Color(0, 0, 0));
        setTitle("Dados do Centro de Formação de Condutores");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Brick house.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(1315, 650));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1315, 650));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTPDadosCFC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTPDadosCFC.setPreferredSize(new java.awt.Dimension(1314, 620));
        jTPDadosCFC.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTPDadosCFCComponentShown(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Telefone:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Celular:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Endereço:");

        jTCelularMatriz.setEditable(false);
        jTCelularMatriz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTEnderecoMatriz.setEditable(false);
        jTEnderecoMatriz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTEnderecoMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEnderecoMatrizActionPerformed(evt);
            }
        });

        jTNomeMatriz.setEditable(false);
        jTNomeMatriz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTTelefoneMatriz.setEditable(false);
        jTTelefoneMatriz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jBAtualizarMatriz.setText("ATUALIZAR");
        jBAtualizarMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarMatrizActionPerformed(evt);
            }
        });

        jLabel6AlterarMatriz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6AlterarMatriz.setText("Nome:");

        jTNomeMatrizAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7AlterarMatriz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7AlterarMatriz.setText("Telefone:");

        jTTelefoneMatrizAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8AlterarMatriz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8AlterarMatriz.setText("Celular:");

        jTCelularMatrizAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPEnderecoAlterarMatriz.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jTNumeroMatrizAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTNumeroMatrizAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNumeroMatrizAlterarActionPerformed(evt);
            }
        });

        jLabel10AlterarMatriz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10AlterarMatriz.setText("Rua:");

        jLabel11AlterarMatriz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11AlterarMatriz.setText("Número: ");

        jTBairroMatrizAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTBairroMatrizAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBairroMatrizAlterarActionPerformed(evt);
            }
        });

        jLabel12AlterarMatriz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12AlterarMatriz.setText("Bairro:");

        jTCEPMatrizAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTCEPMatrizAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCEPMatrizAlterarActionPerformed(evt);
            }
        });

        jLabel13AlterarMatriz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13AlterarMatriz.setText("CEP:");

        jTRuaMatrizAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTRuaMatrizAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRuaMatrizAlterarActionPerformed(evt);
            }
        });

        jLabel14AlterarMatriz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14AlterarMatriz.setText("Cidade: ");

        jTCidadeMatrizAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTCidadeMatrizAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCidadeMatrizAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEnderecoAlterarMatrizLayout = new javax.swing.GroupLayout(jPEnderecoAlterarMatriz);
        jPEnderecoAlterarMatriz.setLayout(jPEnderecoAlterarMatrizLayout);
        jPEnderecoAlterarMatrizLayout.setHorizontalGroup(
            jPEnderecoAlterarMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEnderecoAlterarMatrizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEnderecoAlterarMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12AlterarMatriz)
                    .addComponent(jLabel13AlterarMatriz))
                .addGap(45, 45, 45)
                .addGroup(jPEnderecoAlterarMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPEnderecoAlterarMatrizLayout.createSequentialGroup()
                        .addComponent(jTBairroMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel14AlterarMatriz))
                    .addGroup(jPEnderecoAlterarMatrizLayout.createSequentialGroup()
                        .addComponent(jTCEPMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel11AlterarMatriz)
                        .addGap(18, 18, 18)
                        .addComponent(jTNumeroMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel10AlterarMatriz)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEnderecoAlterarMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTCidadeMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTRuaMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPEnderecoAlterarMatrizLayout.setVerticalGroup(
            jPEnderecoAlterarMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEnderecoAlterarMatrizLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPEnderecoAlterarMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13AlterarMatriz)
                    .addComponent(jTCEPMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11AlterarMatriz)
                    .addComponent(jTNumeroMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10AlterarMatriz)
                    .addComponent(jTRuaMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPEnderecoAlterarMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12AlterarMatriz)
                    .addComponent(jTBairroMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14AlterarMatriz)
                    .addComponent(jTCidadeMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        jLabel1Matriz.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1Matriz.setText("ATUALIZAR DADOS DA MATRIZ");

        jBCancelarAlterarMatriz.setText("CANCELAR");
        jBCancelarAlterarMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarAlterarMatrizActionPerformed(evt);
            }
        });

        jBGravarAlterarMatriz.setText("GRAVAR");
        jBGravarAlterarMatriz.setMaximumSize(new java.awt.Dimension(93, 25));
        jBGravarAlterarMatriz.setMinimumSize(new java.awt.Dimension(93, 25));
        jBGravarAlterarMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarAlterarMatrizActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Diretor de Ensino:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Diretor Geral :");

        jTDiretorGeral.setEditable(false);
        jTDiretorGeral.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTDiretorEnsino.setEditable(false);
        jTDiretorEnsino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPMatrizLayout = new javax.swing.GroupLayout(jPMatriz);
        jPMatriz.setLayout(jPMatrizLayout);
        jPMatrizLayout.setHorizontalGroup(
            jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMatrizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMatrizLayout.createSequentialGroup()
                        .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPMatrizLayout.createSequentialGroup()
                                .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTNomeMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPMatrizLayout.createSequentialGroup()
                                        .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTDiretorGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTTelefoneMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel1))))
                                .addGap(25, 25, 25)
                                .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTCelularMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTDiretorEnsino, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPMatrizLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(40, 40, 40)
                                .addComponent(jTEnderecoMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPMatrizLayout.createSequentialGroup()
                        .addComponent(jPEnderecoAlterarMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMatrizLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMatrizLayout.createSequentialGroup()
                                .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6AlterarMatriz)
                                    .addComponent(jLabel7AlterarMatriz))
                                .addGap(36, 36, 36)
                                .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPMatrizLayout.createSequentialGroup()
                                        .addComponent(jTTelefoneMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(242, 242, 242)
                                        .addComponent(jLabel8AlterarMatriz)
                                        .addGap(65, 65, 65)
                                        .addComponent(jTCelularMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTNomeMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(380, 380, 380))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMatrizLayout.createSequentialGroup()
                                .addComponent(jLabel1Matriz)
                                .addGap(704, 704, 704))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMatrizLayout.createSequentialGroup()
                                .addComponent(jBCancelarAlterarMatriz)
                                .addGap(18, 18, 18)
                                .addComponent(jBGravarAlterarMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(183, 183, 183))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMatrizLayout.createSequentialGroup()
                                .addComponent(jBAtualizarMatriz)
                                .addGap(172, 172, 172))))))
        );
        jPMatrizLayout.setVerticalGroup(
            jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMatrizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNomeMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTDiretorGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTDiretorEnsino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMatrizLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jBAtualizarMatriz))
                    .addGroup(jPMatrizLayout.createSequentialGroup()
                        .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTTelefoneMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTCelularMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTEnderecoMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1Matriz)
                .addGap(13, 13, 13)
                .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNomeMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6AlterarMatriz))
                .addGap(34, 34, 34)
                .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7AlterarMatriz)
                    .addComponent(jTTelefoneMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8AlterarMatriz)
                    .addComponent(jTCelularMatrizAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jPEnderecoAlterarMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelarAlterarMatriz)
                    .addComponent(jBGravarAlterarMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTPDadosCFC.addTab("Matriz", jPMatriz);

        jTableFiliais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableFiliais);

        jBAtualizarFilial.setText("ATUALIZAR");
        jBAtualizarFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarFilialActionPerformed(evt);
            }
        });

        jTNomeFilialAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6AlterarFilial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6AlterarFilial.setText("Nome:");

        jLabel7AlterarFilial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7AlterarFilial.setText("Telefone:");

        jTTelefoneFilialAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8AlterarFilial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8AlterarFilial.setText("Celular:");

        jTCelularFilialAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPEnderecoAlterarFilial.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jTNumeroFilialAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTNumeroFilialAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNumeroFilialAlterarActionPerformed(evt);
            }
        });

        jLabel10AlterarFilial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10AlterarFilial.setText("Rua:");

        jLabel11AlterarFilial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11AlterarFilial.setText("Número: ");

        jTBairroFilialAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTBairroFilialAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBairroFilialAlterarActionPerformed(evt);
            }
        });

        jLabel12AlterarFilial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12AlterarFilial.setText("Bairro:");

        jTCEPFilialAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTCEPFilialAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCEPFilialAlterarActionPerformed(evt);
            }
        });

        jLabel13AlterarFilial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13AlterarFilial.setText("CEP:");

        jTRuaFilialAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTRuaFilialAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRuaFilialAlterarActionPerformed(evt);
            }
        });

        jLabel14AlterarFilial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14AlterarFilial.setText("Cidade: ");

        jTCidadeFilialAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTCidadeFilialAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCidadeFilialAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEnderecoAlterarFilialLayout = new javax.swing.GroupLayout(jPEnderecoAlterarFilial);
        jPEnderecoAlterarFilial.setLayout(jPEnderecoAlterarFilialLayout);
        jPEnderecoAlterarFilialLayout.setHorizontalGroup(
            jPEnderecoAlterarFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEnderecoAlterarFilialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEnderecoAlterarFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13AlterarFilial)
                    .addComponent(jLabel12AlterarFilial))
                .addGap(22, 22, 22)
                .addGroup(jPEnderecoAlterarFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTBairroFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPEnderecoAlterarFilialLayout.createSequentialGroup()
                        .addComponent(jTCEPFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel11AlterarFilial)
                        .addGap(48, 48, 48)
                        .addComponent(jTNumeroFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(jPEnderecoAlterarFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10AlterarFilial)
                    .addComponent(jLabel14AlterarFilial))
                .addGap(18, 18, 18)
                .addGroup(jPEnderecoAlterarFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTCidadeFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTRuaFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPEnderecoAlterarFilialLayout.setVerticalGroup(
            jPEnderecoAlterarFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEnderecoAlterarFilialLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPEnderecoAlterarFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13AlterarFilial)
                    .addComponent(jTCEPFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11AlterarFilial)
                    .addComponent(jTNumeroFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10AlterarFilial)
                    .addComponent(jTRuaFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPEnderecoAlterarFilialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14AlterarFilial)
                    .addComponent(jTCidadeFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12AlterarFilial)
                    .addComponent(jTBairroFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBCancelarAlterarFilial.setText("CANCELAR");
        jBCancelarAlterarFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarAlterarFilialActionPerformed(evt);
            }
        });

        jBGravarAlterarFilial.setText("GRAVAR");
        jBGravarAlterarFilial.setPreferredSize(new java.awt.Dimension(95, 25));
        jBGravarAlterarFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarAlterarFilialActionPerformed(evt);
            }
        });

        jLabel6Filial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6Filial.setText("ATUALIZAR DADOS DA FILIAL");

        jSeparatorFilialAlterar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        javax.swing.GroupLayout jPFiliaisLayout = new javax.swing.GroupLayout(jPFiliais);
        jPFiliais.setLayout(jPFiliaisLayout);
        jPFiliaisLayout.setHorizontalGroup(
            jPFiliaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFiliaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPFiliaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPFiliaisLayout.createSequentialGroup()
                        .addGroup(jPFiliaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparatorFilialAlterar)
                            .addGroup(jPFiliaisLayout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(32, 32, 32)))
                        .addContainerGap())
                    .addGroup(jPFiliaisLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBCancelarAlterarFilial)
                        .addGap(18, 18, 18)
                        .addComponent(jBGravarAlterarFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPFiliaisLayout.createSequentialGroup()
                        .addGroup(jPFiliaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPFiliaisLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBAtualizarFilial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPFiliaisLayout.createSequentialGroup()
                                .addGroup(jPFiliaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6AlterarFilial)
                                    .addComponent(jLabel7AlterarFilial))
                                .addGap(47, 47, 47)
                                .addGroup(jPFiliaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPFiliaisLayout.createSequentialGroup()
                                        .addComponent(jTTelefoneFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(231, 231, 231)
                                        .addComponent(jLabel8AlterarFilial)
                                        .addGap(63, 63, 63)
                                        .addComponent(jTCelularFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTNomeFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(188, 188, 188))
                            .addComponent(jPEnderecoAlterarFilial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPFiliaisLayout.createSequentialGroup()
                .addGap(527, 527, 527)
                .addComponent(jLabel6Filial)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPFiliaisLayout.setVerticalGroup(
            jPFiliaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFiliaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAtualizarFilial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel6Filial)
                .addGap(17, 17, 17)
                .addGroup(jPFiliaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6AlterarFilial)
                    .addComponent(jTNomeFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPFiliaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7AlterarFilial)
                    .addComponent(jTTelefoneFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8AlterarFilial)
                    .addComponent(jTCelularFilialAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPEnderecoAlterarFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPFiliaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGravarAlterarFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelarAlterarFilial))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTPDadosCFC.addTab("Filiais", jPFiliais);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTPDadosCFC, javax.swing.GroupLayout.PREFERRED_SIZE, 1301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPDadosCFC, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved

        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);


    }//GEN-LAST:event_formComponentMoved

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //instrutor não pode atualizar nem matriz nem filial
        if (PermissaoAcesso.getTipoAcesso() == 1) {
            jBAtualizarMatriz.setVisible(false);
            jBAtualizarFilial.setVisible(false);
        }


        /*preenche informações da matriz*/
        Conexao con = new Conexao();
        ResultSet rs;
        String dadosMatriz = "SELECT * "
                + "FROM auto_escola"
                + " WHERE matriz_ou_filial='Matriz'";
        rs = con.executaBusca(dadosMatriz);

        try {
            while (rs.next()) {
                idMatriz = rs.getInt("id_aut");
                nomeMatriz = rs.getString("nome");
                matriz = rs.getString("matriz_ou_filial");
                telefoneMatriz = rs.getString("telefone1");
                cepMatriz = rs.getString("end_cep");
                cidadeMatriz = rs.getString("end_cidade");
                ruaMatriz = rs.getString("end_rua");
                numeroMatriz = rs.getString("end_numero");
                bairroMatriz = rs.getString("end_bairro");
                celularMatriz = rs.getString("telefone2");
            }

            jTNomeMatriz.setText(nomeMatriz);
            jTTelefoneMatriz.setText(telefoneMatriz);
            jTEnderecoMatriz.setText("Rua/Avenida: " + ruaMatriz + ", n. " + numeroMatriz + ", bairro: " + bairroMatriz + ", " + cepMatriz + ", " + cidadeMatriz);
            jTCelularMatriz.setText(celularMatriz);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //nome do diretor geral da matriz
        con = new Conexao();
        rs = null;
        String nomeDiretorGeral = "select distinct F.nome "
                + "from funcionario F, diretor D, auto_escola AE "
                + "where D.funcao='DIRETOR GERAL'and D.cpf_func=F.cpf_func and AE.matriz_ou_filial='Matriz'";
        rs = con.executaBusca(nomeDiretorGeral);
        try {
            while (rs.next()) {
                jTDiretorGeral.setText(rs.getString("nome"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        //nome do diretor de ensino da matriz
        con = new Conexao();
        rs = null;
        String nomeDiretorEnsino = "select distinct F.nome "
                + "from funcionario F, diretor D, auto_escola AE "
                + "where D.funcao='DIRETOR DE ENSINO'and D.cpf_func=F.cpf_func and AE.matriz_ou_filial='Matriz'";
        rs = con.executaBusca(nomeDiretorEnsino);
        try {
            while (rs.next()) {
                jTDiretorEnsino.setText(rs.getString("nome"));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        //se a autoescola for matriz, só poderá alterar a matriz
        if (PermissaoAcesso.getIdAutoEscola() == idMatriz) {
            jBAtualizarFilial.setVisible(false);
        } else {//se for filial só pode alterar filial
            jBAtualizarMatriz.setVisible(false);
            idFilial = PermissaoAcesso.getIdAutoEscola();
        }


        /*preenche informações das filiais*/
        con = new Conexao();
        String dadosFiliais = "SELECT AE.id_aut AS id,AE.nome,AE.telefone1 AS Telefone,AE.end_cep AS CEP,AE.end_cidade AS Cidade,AE.end_rua AS Rua,AE.end_numero AS N,AE.end_bairro AS Bairro, "
                + "AE.telefone2 AS Celular,F.nome AS Diretor_Geral,FUN.nome AS Diretor_Ensino "
                + "FROM auto_escola AE, funcionario F, diretor D,diretor DI,funcionario FUN "
                + "WHERE AE.matriz_ou_filial='Matriz' and D.funcao='DIRETOR GERAL'and D.cpf_func=F.cpf_func and F.id_aut=AE.id_aut and "
                + "   DI.funcao='DIRETOR DE ENSINO'and DI.cpf_func=FUN.cpf_func and FUN.id_aut=AE.id_aut";
        PreparedStatement ps = null;
        try {
            ps = con.getConexao().prepareStatement(dadosFiliais);
            rs = ps.executeQuery();
            jTableFiliais.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(TelaDadosCFC.class.getName()).log(Level.SEVERE, null, ex);
        }
       

    }//GEN-LAST:event_formComponentShown

    private void jTPDadosCFCComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTPDadosCFCComponentShown

    }//GEN-LAST:event_jTPDadosCFCComponentShown

    private void jBAtualizarFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarFilialActionPerformed
        //mostra campo de id
        jLabel6Filial.setVisible(true);
        jSeparatorFilialAlterar.setVisible(true);

        Conexao con = new Conexao();
        ResultSet rs;
        if (idFilial > 0) {
            String dadosFilialProcurada = "SELECT nome,matriz_ou_filial,telefone1,end_cep,end_cidade,end_rua,end_numero,end_bairro,telefone2 FROM auto_escola "
                    + "WHERE matriz_ou_filial='Filial' AND id_aut=" + idFilial;

            int controle = 0;
            rs = con.executaBusca(dadosFilialProcurada);
            try {

                while (rs.next()) {
                    nomeFilial = rs.getString("nome");
                    filial = rs.getString("matriz_ou_filial");
                    telefoneFilial = rs.getString("telefone1");
                    cepFilial = rs.getString("end_cep");
                    cidadeFilial = rs.getString("end_cidade");
                    ruaFilial = rs.getString("end_rua");
                    numeroFilial = rs.getString("end_numero");
                    bairroFilial = rs.getString("end_bairro");
                    celularFilial = rs.getString("telefone2");
                }
                if (nomeFilial == null || nomeFilial == "") {
                    JOptionPane.showMessageDialog(null, "ID Inválido! Por favor, insira um id válido!");
                    jLabel6Filial.setVisible(true);
                    controle = 1;
                }

                //preenche campos com dados atuais
                if (controle != 1) {
                    jTNomeFilialAlterar.setVisible(true);
                    jTRuaFilialAlterar.setVisible(true);
                    jTNumeroFilialAlterar.setVisible(true);
                    jTCEPFilialAlterar.setVisible(true);
                    jTBairroFilialAlterar.setVisible(true);
                    jTCidadeFilialAlterar.setVisible(true);
                    jTCelularFilialAlterar.setVisible(true);
                    jTTelefoneFilialAlterar.setVisible(true);
                    jSeparatorFilialAlterar.setVisible(true);
                    jPEnderecoAlterarFilial.setVisible(true);
                    jLabel10AlterarFilial.setVisible(true);
                    jLabel11AlterarFilial.setVisible(true);
                    jLabel12AlterarFilial.setVisible(true);
                    jLabel13AlterarFilial.setVisible(true);
                    jLabel14AlterarFilial.setVisible(true);
                    jLabel6AlterarFilial.setVisible(true);
                    jLabel7AlterarFilial.setVisible(true);
                    jLabel8AlterarFilial.setVisible(true);
                    jBCancelarAlterarFilial.setVisible(true);
                    jBGravarAlterarFilial.setVisible(true);
                    jTNomeFilialAlterar.setText(nomeFilial);
                    jTRuaFilialAlterar.setText(ruaFilial);
                    jTNumeroFilialAlterar.setText(numeroFilial);
                    jTCEPFilialAlterar.setText(cepFilial);
                    jTBairroFilialAlterar.setText(bairroFilial);
                    jTCidadeFilialAlterar.setText(cidadeFilial);
                    jTCelularFilialAlterar.setText(celularFilial);
                    jTTelefoneFilialAlterar.setText(telefoneFilial);

                    jBCancelarAlterarFilial.setVisible(true);
                    jBGravarAlterarFilial.setVisible(true);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro, tente novamente!");
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Filial não pode ser alterada!");
        }

    }//GEN-LAST:event_jBAtualizarFilialActionPerformed

    private void jBCancelarAlterarFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarAlterarFilialActionPerformed

        //esconde campos
        jLabel6Filial.setVisible(false);
        jTNomeFilialAlterar.setVisible(false);
        jTRuaFilialAlterar.setVisible(false);
        jTNumeroFilialAlterar.setVisible(false);
        jTCEPFilialAlterar.setVisible(false);
        jTBairroFilialAlterar.setVisible(false);
        jTCidadeFilialAlterar.setVisible(false);
        jTCelularFilialAlterar.setVisible(false);
        jTTelefoneFilialAlterar.setVisible(false);
        jSeparatorFilialAlterar.setVisible(false);
        jPEnderecoAlterarFilial.setVisible(false);
        jLabel10AlterarFilial.setVisible(false);
        jLabel11AlterarFilial.setVisible(false);
        jLabel12AlterarFilial.setVisible(false);
        jLabel13AlterarFilial.setVisible(false);
        jLabel14AlterarFilial.setVisible(false);
        jLabel6AlterarFilial.setVisible(false);
        jLabel7AlterarFilial.setVisible(false);
        jLabel8AlterarFilial.setVisible(false);
        jBCancelarAlterarFilial.setVisible(false);
        jBGravarAlterarFilial.setVisible(false);
    }//GEN-LAST:event_jBCancelarAlterarFilialActionPerformed

    private void jBGravarAlterarFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarAlterarFilialActionPerformed
        String novoNome = jTNomeFilialAlterar.getText();
        String novaRua = jTRuaFilialAlterar.getText();
        String novoNumero = jTNumeroFilialAlterar.getText();
        String novoCep = jTCEPFilialAlterar.getText();
        String novoBairro = jTBairroFilialAlterar.getText();
        String novaCidade = jTCidadeFilialAlterar.getText();
        String novoCelular = jTCelularFilialAlterar.getText();
        String novoTelefone = jTTelefoneFilialAlterar.getText();

        OperacoesBancoDeDados atualizaDados = new OperacoesBancoDeDados();
        String tabela = "auto_escola";
        String condicao = "id_aut=" + idFilial;

        int res1 = atualizaDados.atualizarLinhasBD(tabela, "nome", "'" + novoNome + "'", condicao);
        int res2 = atualizaDados.atualizarLinhasBD(tabela, "telefone1", "'" + novoTelefone + "'", condicao);
        int res3 = atualizaDados.atualizarLinhasBD(tabela, "end_cep", "'" + novoCep + "'", condicao);
        int res4 = atualizaDados.atualizarLinhasBD(tabela, "end_cidade", "'" + novaCidade + "'", condicao);
        int res5 = atualizaDados.atualizarLinhasBD(tabela, "end_rua", "'" + novaRua + "'", condicao);
        int res6 = atualizaDados.atualizarLinhasBD(tabela, "end_numero", "'" + novoNumero + "'", condicao);
        int res7 = atualizaDados.atualizarLinhasBD(tabela, "end_bairro", "'" + novoBairro + "'", condicao);
        int res8 = atualizaDados.atualizarLinhasBD(tabela, "telefone2", "'" + novoCelular + "'", condicao);
        if (res1 > 0 && res2 > 0 && res3 > 0 && res4 > 0 && res5 > 0 && res6 > 0 && res7 > 0 && res8 > 0) {
            JOptionPane.showMessageDialog(null, "Atualização realizada com sucesso!");
            //esconde campos

            jLabel6Filial.setVisible(false);
            jTNomeFilialAlterar.setVisible(false);
            jTRuaFilialAlterar.setVisible(false);
            jTNumeroFilialAlterar.setVisible(false);
            jTCEPFilialAlterar.setVisible(false);
            jTBairroFilialAlterar.setVisible(false);
            jTCidadeFilialAlterar.setVisible(false);
            jTCelularFilialAlterar.setVisible(false);
            jTTelefoneFilialAlterar.setVisible(false);
            jSeparatorFilialAlterar.setVisible(false);
            jPEnderecoAlterarFilial.setVisible(false);
            jLabel10AlterarFilial.setVisible(false);
            jLabel11AlterarFilial.setVisible(false);
            jLabel12AlterarFilial.setVisible(false);
            jLabel13AlterarFilial.setVisible(false);
            jLabel14AlterarFilial.setVisible(false);
            jLabel6AlterarFilial.setVisible(false);
            jLabel7AlterarFilial.setVisible(false);
            jLabel8AlterarFilial.setVisible(false);
            jBCancelarAlterarFilial.setVisible(false);
            jBGravarAlterarFilial.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro!!! Feche a janela, abra novamente, confira os dados atualizados e tente outra vez!");
        }
    }//GEN-LAST:event_jBGravarAlterarFilialActionPerformed

    private void jBCancelarAlterarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarAlterarMatrizActionPerformed

        //esconde campos
        jTNomeMatrizAlterar.setVisible(false);
        jTRuaMatrizAlterar.setVisible(false);
        jTNumeroMatrizAlterar.setVisible(false);
        jTCEPMatrizAlterar.setVisible(false);
        jTBairroMatrizAlterar.setVisible(false);
        jTCidadeMatrizAlterar.setVisible(false);
        jTCelularMatrizAlterar.setVisible(false);
        jTTelefoneMatrizAlterar.setVisible(false);
        jSeparator1.setVisible(false);
        jPEnderecoAlterarMatriz.setVisible(false);
        jLabel10AlterarMatriz.setVisible(false);
        jLabel11AlterarMatriz.setVisible(false);
        jLabel12AlterarMatriz.setVisible(false);
        jLabel13AlterarMatriz.setVisible(false);
        jLabel14AlterarMatriz.setVisible(false);
        jLabel6AlterarMatriz.setVisible(false);
        jLabel7AlterarMatriz.setVisible(false);
        jLabel8AlterarMatriz.setVisible(false);
        jBCancelarAlterarMatriz.setVisible(false);
        jBGravarAlterarMatriz.setVisible(false);
    }//GEN-LAST:event_jBCancelarAlterarMatrizActionPerformed

    private void jBGravarAlterarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarAlterarMatrizActionPerformed

        String novoNome = jTNomeMatrizAlterar.getText();
        String novaRua = jTRuaMatrizAlterar.getText();
        String novoNumero = jTNumeroMatrizAlterar.getText();
        String novoCep = jTCEPMatrizAlterar.getText();
        String novoBairro = jTBairroMatrizAlterar.getText();
        String novaCidade = jTCidadeMatrizAlterar.getText();
        String novoCelular = jTCelularMatrizAlterar.getText();
        String novoTelefone = jTTelefoneMatrizAlterar.getText();

        OperacoesBancoDeDados atualizaDados = new OperacoesBancoDeDados();
        String tabela = "auto_escola";
        String condicao = "matriz_ou_filial='Matriz'";

        int res1 = atualizaDados.atualizarLinhasBD(tabela, "nome", "'" + novoNome + "'", condicao);
        int res2 = atualizaDados.atualizarLinhasBD(tabela, "telefone1", "'" + novoTelefone + "'", condicao);
        int res3 = atualizaDados.atualizarLinhasBD(tabela, "end_cep", "'" + novoCep + "'", condicao);
        int res4 = atualizaDados.atualizarLinhasBD(tabela, "end_cidade", "'" + novaCidade + "'", condicao);
        int res5 = atualizaDados.atualizarLinhasBD(tabela, "end_rua", "'" + novaRua + "'", condicao);
        int res6 = atualizaDados.atualizarLinhasBD(tabela, "end_numero", "'" + novoNumero + "'", condicao);
        int res7 = atualizaDados.atualizarLinhasBD(tabela, "end_bairro", "'" + novoBairro + "'", condicao);
        int res8 = atualizaDados.atualizarLinhasBD(tabela, "telefone2", "'" + novoCelular + "'", condicao);
        if (res1 > 0 && res2 > 0 && res3 > 0 && res4 > 0 && res5 > 0 && res6 > 0 && res7 > 0 && res8 > 0) {
            JOptionPane.showMessageDialog(null, "Atualização realizada com sucesso!");
            //esconde campos
            jLabel1Matriz.setVisible(false);
            jTNomeMatrizAlterar.setVisible(false);
            jTRuaMatrizAlterar.setVisible(false);
            jTNumeroMatrizAlterar.setVisible(false);
            jTCEPMatrizAlterar.setVisible(false);
            jTBairroMatrizAlterar.setVisible(false);
            jTCidadeMatrizAlterar.setVisible(false);
            jTCelularMatrizAlterar.setVisible(false);
            jTTelefoneMatrizAlterar.setVisible(false);
            jSeparator1.setVisible(false);
            jPEnderecoAlterarMatriz.setVisible(false);
            jLabel10AlterarMatriz.setVisible(false);
            jLabel11AlterarMatriz.setVisible(false);
            jLabel12AlterarMatriz.setVisible(false);
            jLabel13AlterarMatriz.setVisible(false);
            jLabel14AlterarMatriz.setVisible(false);
            jLabel6AlterarMatriz.setVisible(false);
            jLabel7AlterarMatriz.setVisible(false);
            jLabel8AlterarMatriz.setVisible(false);
            jBCancelarAlterarMatriz.setVisible(false);
            jBGravarAlterarMatriz.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro!!! Feche a janela, abra novamente, confira os dados atualizados e tente outra vez!");
        }
    }//GEN-LAST:event_jBGravarAlterarMatrizActionPerformed

    private void jTCidadeMatrizAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCidadeMatrizAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCidadeMatrizAlterarActionPerformed

    private void jTRuaMatrizAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRuaMatrizAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRuaMatrizAlterarActionPerformed

    private void jTCEPMatrizAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCEPMatrizAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCEPMatrizAlterarActionPerformed

    private void jTBairroMatrizAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBairroMatrizAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBairroMatrizAlterarActionPerformed

    private void jTNumeroMatrizAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNumeroMatrizAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNumeroMatrizAlterarActionPerformed

    private void jBAtualizarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarMatrizActionPerformed
        //mostra campos
        jLabel1Matriz.setVisible(true);
        jTNomeMatrizAlterar.setVisible(true);
        jTRuaMatrizAlterar.setVisible(true);
        jTNumeroMatrizAlterar.setVisible(true);
        jTCEPMatrizAlterar.setVisible(true);
        jTBairroMatrizAlterar.setVisible(true);
        jTCidadeMatrizAlterar.setVisible(true);
        jTCelularMatrizAlterar.setVisible(true);
        jTTelefoneMatrizAlterar.setVisible(true);
        jSeparator1.setVisible(true);
        jPEnderecoAlterarMatriz.setVisible(true);
        jLabel10AlterarMatriz.setVisible(true);
        jLabel11AlterarMatriz.setVisible(true);
        jLabel12AlterarMatriz.setVisible(true);
        jLabel13AlterarMatriz.setVisible(true);
        jLabel14AlterarMatriz.setVisible(true);
        jLabel6AlterarMatriz.setVisible(true);
        jLabel7AlterarMatriz.setVisible(true);
        jLabel8AlterarMatriz.setVisible(true);
        jBCancelarAlterarMatriz.setVisible(true);
        jBGravarAlterarMatriz.setVisible(true);

        //preenche campos com dados atuais
        jTNomeMatrizAlterar.setText(nomeMatriz);
        jTRuaMatrizAlterar.setText(ruaMatriz);
        jTNumeroMatrizAlterar.setText(numeroMatriz);
        jTCEPMatrizAlterar.setText(cepMatriz);
        jTBairroMatrizAlterar.setText(bairroMatriz);
        jTCidadeMatrizAlterar.setText(cidadeMatriz);
        jTCelularMatrizAlterar.setText(celularMatriz);
        jTTelefoneMatrizAlterar.setText(telefoneMatriz);

    }//GEN-LAST:event_jBAtualizarMatrizActionPerformed

    private void jTEnderecoMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEnderecoMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTEnderecoMatrizActionPerformed

    private void jTCidadeFilialAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCidadeFilialAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCidadeFilialAlterarActionPerformed

    private void jTRuaFilialAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRuaFilialAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRuaFilialAlterarActionPerformed

    private void jTCEPFilialAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCEPFilialAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCEPFilialAlterarActionPerformed

    private void jTBairroFilialAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBairroFilialAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBairroFilialAlterarActionPerformed

    private void jTNumeroFilialAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNumeroFilialAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNumeroFilialAlterarActionPerformed

    public void setPosicao() {

        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizarFilial;
    private javax.swing.JButton jBAtualizarMatriz;
    private javax.swing.JButton jBCancelarAlterarFilial;
    private javax.swing.JButton jBCancelarAlterarMatriz;
    private javax.swing.JButton jBGravarAlterarFilial;
    private javax.swing.JButton jBGravarAlterarMatriz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10AlterarFilial;
    private javax.swing.JLabel jLabel10AlterarMatriz;
    private javax.swing.JLabel jLabel11AlterarFilial;
    private javax.swing.JLabel jLabel11AlterarMatriz;
    private javax.swing.JLabel jLabel12AlterarFilial;
    private javax.swing.JLabel jLabel12AlterarMatriz;
    private javax.swing.JLabel jLabel13AlterarFilial;
    private javax.swing.JLabel jLabel13AlterarMatriz;
    private javax.swing.JLabel jLabel14AlterarFilial;
    private javax.swing.JLabel jLabel14AlterarMatriz;
    private javax.swing.JLabel jLabel1Matriz;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6AlterarFilial;
    private javax.swing.JLabel jLabel6AlterarMatriz;
    private javax.swing.JLabel jLabel6Filial;
    private javax.swing.JLabel jLabel7AlterarFilial;
    private javax.swing.JLabel jLabel7AlterarMatriz;
    private javax.swing.JLabel jLabel8AlterarFilial;
    private javax.swing.JLabel jLabel8AlterarMatriz;
    private javax.swing.JPanel jPEnderecoAlterarFilial;
    private javax.swing.JPanel jPEnderecoAlterarMatriz;
    private javax.swing.JPanel jPFiliais;
    private javax.swing.JPanel jPMatriz;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparatorFilialAlterar;
    private javax.swing.JTextField jTBairroFilialAlterar;
    private javax.swing.JTextField jTBairroMatrizAlterar;
    private javax.swing.JTextField jTCEPFilialAlterar;
    private javax.swing.JTextField jTCEPMatrizAlterar;
    private javax.swing.JTextField jTCelularFilialAlterar;
    private javax.swing.JTextField jTCelularMatriz;
    private javax.swing.JTextField jTCelularMatrizAlterar;
    private javax.swing.JTextField jTCidadeFilialAlterar;
    private javax.swing.JTextField jTCidadeMatrizAlterar;
    private javax.swing.JTextField jTDiretorEnsino;
    private javax.swing.JTextField jTDiretorGeral;
    private javax.swing.JTextField jTEnderecoMatriz;
    private javax.swing.JTextField jTNomeFilialAlterar;
    private javax.swing.JTextField jTNomeMatriz;
    private javax.swing.JTextField jTNomeMatrizAlterar;
    private javax.swing.JTextField jTNumeroFilialAlterar;
    private javax.swing.JTextField jTNumeroMatrizAlterar;
    private javax.swing.JTabbedPane jTPDadosCFC;
    private javax.swing.JTextField jTRuaFilialAlterar;
    private javax.swing.JTextField jTRuaMatrizAlterar;
    private javax.swing.JTextField jTTelefoneFilialAlterar;
    private javax.swing.JTextField jTTelefoneMatriz;
    private javax.swing.JTextField jTTelefoneMatrizAlterar;
    private javax.swing.JTable jTableFiliais;
    // End of variables declaration//GEN-END:variables

}
