/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ConexaoPostgres.Conexao;
import codigo.PermissaoAcesso;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author USUARIO
 */
public class TelaVerificaDisponibilidadePratica extends javax.swing.JFrame {

    /**
     * Creates new form TelaVerificaDisponibilidadePratica
     */
    public TelaVerificaDisponibilidadePratica() {
        initComponents();
        iniciar();
    }

    
    public void iniciar() {
        /*preenche informações da tabela*/
        Conexao con = new Conexao();
        String disponibilidade= "select F.nome,F.cpf_func,CA.hora_inicio,CA.hora_fim,V.placa "
                + "from conjunto_aulas CA,veiculos V,funcionario F,usado U "
                + "where F.nome='"+TelaMatricularPratico.getInstrutor()+"' and F.cpf_func=CA.cpf_func and V.placa='"+TelaMatricularPratico.getPlacaCarro()+"' and V.placa=U.placa and "
                + "u.id_conj_aulas=CA.id_conj_aulas and V.id_aut="+PermissaoAcesso.getIdAutoEscola()+" and CA.hora_inicio!='CONCLUIDO' and CA.hora_fim!='CONCLUIDO' ";
        PreparedStatement ps = null;
        ResultSet rs = null;
               System.out.println("instrutor =" + TelaMatricularPratico.getInstrutor() +"placa="+TelaMatricularPratico.getPlacaCarro());
        try {
            ps = con.getConexao().prepareStatement(disponibilidade);
            rs = ps.executeQuery();
            jTableVerificarDisponibilidade.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao manipular dados, verifique os dados");
            //Logger.getLogger(TelaDadosCFC.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDisponibilidadeVeiculo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVerificarDisponibilidade = new javax.swing.JTable();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelDisponibilidadeVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Horários já preenchidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jTableVerificarDisponibilidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableVerificarDisponibilidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVerificarDisponibilidadeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVerificarDisponibilidade);

        jButtonSair.setText("SAIR");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDisponibilidadeVeiculoLayout = new javax.swing.GroupLayout(jPanelDisponibilidadeVeiculo);
        jPanelDisponibilidadeVeiculo.setLayout(jPanelDisponibilidadeVeiculoLayout);
        jPanelDisponibilidadeVeiculoLayout.setHorizontalGroup(
            jPanelDisponibilidadeVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDisponibilidadeVeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDisponibilidadeVeiculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanelDisponibilidadeVeiculoLayout.setVerticalGroup(
            jPanelDisponibilidadeVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDisponibilidadeVeiculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDisponibilidadeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDisponibilidadeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableVerificarDisponibilidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVerificarDisponibilidadeMouseClicked
        // TODO add your handling code here:

        /**
        * AÇÃO AO CLICAR NA TABELA
        */
        /*if(evt.getClickCount() == 1){ Object obj = (tbBateriasPedido.getValueAt(tbBateriasPedido.getSelectedRow(), 0)); String Id = obj.toString(); tfIdBateria.setText(Id);
            //aqui pego o valor da linha selecionada na coluna 0 e adiciono ao jtextfield } }*/
    }//GEN-LAST:event_jTableVerificarDisponibilidadeMouseClicked

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair;
    private javax.swing.JPanel jPanelDisponibilidadeVeiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVerificarDisponibilidade;
    // End of variables declaration//GEN-END:variables
}
